export const navigatorCopy = {
  en: {
    language: "English", title: "Afghan Hub AI Navigator", beta: "Discovery beta", description: "Find the right people, possibilities, and next steps.",
    placeholder: "What are you looking to achieve today?", search: "Search", guide: "Not sure where to start?", guideDescription: "Answer a few quick questions and we'll help you find your path.",
    goalsTitle: "What brings you to Afghan Hub today?", topicsTitle: "Which area interests you most?", locationTitle: "Where would you like to connect?", eventLocationTitle: "Where would you like to attend events?",
    goals: ["Meet people", "Find opportunities", "Grow my work or business", "Connect with organizations", "Explore events", "I'm still exploring"],
    topics: ["Technology", "Arts & Culture", "Education", "Business", "Community & Social Impact"],
    prompts: ["Technology opportunities in British Columbia", "Organizations supporting newcomers", "Events this month", "Artists & Creatives"],
    custom: "Or tell us in your own words", location: "City or region (optional)", back: "Back", skip: "Skip", next: "Continue", restart: "Restart", find: "Find my path", close: "Close guided discovery",
    searching: "Searching public listings…", empty: "No matching public listings found.", error: "Search is temporarily unavailable. Please try again.", rate: "The Navigator is busy. Please wait a minute and try again.", retry: "Try again", results: "Your next steps", looking: "Looking for", all: "All interests", anywhere: "Any location", browse: "Explore more", people: "Sign in to discover people", peopleNote: "Member profiles are available inside the signed-in network.", partial: "Some directories are temporarily unavailable. Available results are shown below.", recovery: "Try a broader interest or another location, or explore a directory.", reason: "Matches your interest", locationReason: "Matches your location or is available remotely", generalReason: "A public listing in your selected area", clearLocation: "Search any location", privacy: "How discovery works", disclosure: "This beta uses structured search, not a language model. It searches published public listings only. Member discovery continues in the signed-in Community Navigator. Your conversation stays in this page session; search text is not logged. Results are limited to matching public listings and may not cover every listing. Content is shown in its original language.", history: "Search history", step: "Question", types: {businesses:"Businesses",organizations:"Organizations",opportunities:"Opportunities",events:"Events"},
  },
  fa: {
    language: "فارسی", title: "راهنمای هوشمند افغان هاب", beta: "نسخه آزمایشی", description: "افراد، فرصت‌ها و گام بعدی خود را پیدا کنید.",
    placeholder: "امروز می‌خواهید به چه هدفی برسید؟", search: "جست‌وجو", guide: "نمی‌دانید از کجا شروع کنید؟", guideDescription: "به چند پرسش کوتاه پاسخ دهید تا مسیر خود را پیدا کنید.",
    goalsTitle: "امروز برای چه به افغان هاب آمده‌اید؟", topicsTitle: "به کدام حوزه علاقه دارید؟", locationTitle: "در کجا می‌خواهید ارتباط برقرار کنید؟", eventLocationTitle: "در کجا می‌خواهید در رویدادها شرکت کنید؟",
    goals: ["آشنایی با افراد", "پیدا کردن فرصت‌ها", "رشد کار یا کسب‌وکار", "ارتباط با سازمان‌ها", "رویدادها", "هنوز در حال بررسی هستم"],
    topics: ["فناوری", "هنر و فرهنگ", "آموزش", "کسب‌وکار", "جامعه و تأثیر اجتماعی"],
    prompts: ["فرصت‌های فناوری در بریتیش کلمبیا", "سازمان‌های پشتیبان تازه‌واردان", "رویدادهای این ماه", "هنرمندان و خلاقان"],
    custom: "یا با کلمات خود توضیح دهید", location: "شهر یا منطقه (اختیاری)", back: "بازگشت", skip: "رد کردن", next: "ادامه", restart: "شروع دوباره", find: "مسیرم را پیدا کن", close: "بستن راهنما",
    searching: "در حال جست‌وجوی فهرست‌های عمومی…", empty: "نتیجه عمومی مرتبطی پیدا نشد.", error: "جست‌وجو فعلاً در دسترس نیست. دوباره تلاش کنید.", rate: "راهنما مشغول است. یک دقیقه صبر کنید و دوباره تلاش کنید.", retry: "تلاش دوباره", results: "گام‌های بعدی شما", looking: "در جست‌وجوی", all: "همه علاقه‌ها", anywhere: "همه مکان‌ها", browse: "بیشتر ببینید", people: "برای آشنایی با افراد وارد شوید", peopleNote: "پروفایل اعضا در شبکه پس از ورود در دسترس است.", partial: "برخی فهرست‌ها فعلاً در دسترس نیستند. نتایج موجود در زیر آمده است.", recovery: "موضوع گسترده‌تر یا مکان دیگری را امتحان کنید یا فهرست‌ها را ببینید.", reason: "مرتبط با علاقه شما", locationReason: "مرتبط با مکان شما یا قابل دسترسی از راه دور", generalReason: "یک فهرست عمومی در حوزه انتخابی شما", clearLocation: "جست‌وجو در همه مکان‌ها", privacy: "روش جست‌وجو", disclosure: "این نسخه از جست‌وجوی ساختاریافته استفاده می‌کند، نه مدل زبانی. فقط فهرست‌های عمومی منتشرشده جست‌وجو می‌شوند. افراد را در راهنمای اعضا پس از ورود پیدا کنید. گفتگو فقط در همین نشست صفحه می‌ماند؛ متن جست‌وجو ثبت نمی‌شود. نتایج محدودند و ممکن است همه موارد را پوشش ندهند. محتوا به زبان اصلی نمایش داده می‌شود.", history: "تاریخچه جست‌وجو", step: "پرسش", types: {businesses:"کسب‌وکارها",organizations:"سازمان‌ها",opportunities:"فرصت‌ها",events:"رویدادها"},
  },
  ps: {
    language: "پښتو", title: "د افغان هب هوښیار لارښود", beta: "ازمایښتي نسخه", description: "خلک، فرصتونه او خپل راتلونکی ګام ومومئ.",
    placeholder: "نن څه ترلاسه کول غواړئ؟", search: "لټون", guide: "نه پوهېږئ له کومه پیل وکړئ؟", guideDescription: "څو لنډې پوښتنې ځواب کړئ او خپله لاره ومومئ.",
    goalsTitle: "نن افغان هب ته د څه لپاره راغلي یاست؟", topicsTitle: "کومه برخه مو خوښېږي؟", locationTitle: "چېرته اړیکې جوړول غواړئ؟", eventLocationTitle: "چېرته په غونډو کې ګډون کول غواړئ؟",
    goals: ["له خلکو سره پېژندنه", "د فرصتونو موندل", "د کار یا کاروبار وده", "له سازمانونو سره اړیکې", "د غونډو لټون", "لا هم ګورم"],
    topics: ["ټکنالوژي", "هنر او کلتور", "زده کړه", "کاروبار", "ټولنه او ټولنیز اغېز"],
    prompts: ["په بریټش کولمبیا کې د ټکنالوژۍ فرصتونه", "د نویو راغلو ملاتړي سازمانونه", "د دې میاشتې غونډې", "هنرمندان او نوښتګر"],
    custom: "یا په خپلو کلمو یې ووایاست", location: "ښار یا سیمه (اختیاري)", back: "شاته", skip: "تېرېدل", next: "دوام", restart: "بیا پیل", find: "زما لاره ومومه", close: "لارښود بند کړئ",
    searching: "د عامه لېستونو لټون روان دی…", empty: "اړوند عامه پایله ونه موندل شوه.", error: "لټون اوس شتون نه لري. بیا هڅه وکړئ.", rate: "لارښود بوخت دی. یوه دقیقه صبر وکړئ او بیا هڅه وکړئ.", retry: "بیا هڅه", results: "ستاسو راتلونکي ګامونه", looking: "د موندلو لپاره", all: "ټولې علاقې", anywhere: "هر ځای", browse: "نور وګورئ", people: "د خلکو د موندلو لپاره ننوځئ", peopleNote: "د غړو پروفایلونه له ننوتلو وروسته په شبکه کې شته.", partial: "ځینې لېستونه اوس شتون نه لري. شته پایلې لاندې ښودل کېږي.", recovery: "پراخه موضوع یا بل ځای وازمویئ، یا لېستونه وګورئ.", reason: "ستاسو له علاقې سره تړاو لري", locationReason: "ستاسو له ځای سره تړاو لري یا له لرې شته", generalReason: "ستاسو په ټاکل شوې برخه کې عامه لېست", clearLocation: "په هر ځای کې لټون", privacy: "لټون څنګه کار کوي", disclosure: "دا نسخه جوړښتي لټون کاروي، نه ژبنی ماډل. یوازې خپاره شوي عامه لېستونه لټوي. د غړو موندنه له ننوتلو وروسته په لارښود کې دوام لري. خبرې یوازې د دې پاڼې په ناسته کې پاتې کېږي؛ د لټون متن نه ثبتېږي. پایلې محدودې دي او ښايي ټول لېستونه ونه پوښي. منځپانګه په اصلي ژبه ښودل کېږي.", history: "د لټون تاریخ", step: "پوښتنه", types: {businesses:"کاروبارونه",organizations:"سازمانونه",opportunities:"فرصتونه",events:"غونډې"},
  },
} as const;
export type NavigatorLanguage = "en" | "fa" | "fa-AF" | "ps";
export const guidedGoals = ["Meet people", "Find opportunities", "Grow my work or business", "Connect with organizations", "Explore events", "I'm still exploring"];
export const guidedTopics = ["technology", "arts", "education", "business", "community"];
