import { setBusinessVerification } from "@/app/(dashboard)/businesses/actions";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck } from "lucide-react";
import { ExternalImage } from "@/components/ui/external-image";
import { createClient } from "@/lib/supabase/server";

type BusinessPageProps={params:Promise<{slug:string}>;searchParams:Promise<{error?:string}>};
export default async function BusinessPage({params,searchParams}:BusinessPageProps){
 const {slug}=await params; const {error:actionError}=await searchParams; const supabase=await createClient();
 const {data:business,error}=await supabase.from("businesses").select(`id,name,slug,category,short_description,description,services,website_url,email,phone,address_line,city,province_state,country,logo_url,cover_url,is_verified,is_hiring,status,moderation_note,owner_id`).eq("slug",slug).maybeSingle();
 if(error||!business)notFound();
 const {data:{user}}=await supabase.auth.getUser();
 const {data:viewerProfile}=user?await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle():{data:null};
 const canEdit=user?.id===business.owner_id; const canVerify=viewerProfile?.role==="admin"&&business.status==="published";
 const services=Array.isArray(business.services)?business.services.filter((service:unknown):service is string=>typeof service==="string"):[];
 const location=[business.city,business.province_state,business.country].filter(Boolean).join(", ");
 return <main className="px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl">
  <Link href="/businesses" className="text-sm font-medium text-primary hover:opacity-80">← Back to businesses</Link>
  {actionError?<div className="mt-6 rounded-xl border border-destructive/20 bg-destructive/5 p-4 text-sm text-destructive">{actionError}</div>:null}
  {business.status!=="published"?<div className="mt-6 rounded-xl border border-accent/50 bg-accent/40 p-4 text-sm text-accent-foreground">{business.status==="draft"?"This business is waiting for moderator approval and is not visible to the community yet.":`This business was not approved.${business.moderation_note?` Reason: ${business.moderation_note}`:""} Edit it to submit it for review again.`}</div>:null}
  <section className="surface-panel mt-6 overflow-hidden rounded-3xl">{business.cover_url?<ExternalImage src={business.cover_url} alt={`${business.name} cover`} width={1200} height={400} className="h-40 w-full object-cover md:h-56"/>:<div className="h-40 bg-[radial-gradient(circle_at_20%_20%,color-mix(in_oklab,var(--primary)_10%,transparent),transparent_35%),linear-gradient(to_right,var(--muted),var(--card))] md:h-56"/>}
   <div className="px-6 pb-8 md:px-10"><div className="-mt-12 flex flex-col gap-5 sm:flex-row sm:items-end">{business.logo_url?<ExternalImage src={business.logo_url} alt={`${business.name} logo`} width={96} height={96} className="size-24 rounded-2xl border-4 border-card object-cover shadow-sm"/>:<div className="flex size-24 items-center justify-center rounded-2xl border-4 border-card bg-primary/10 text-3xl font-bold text-primary shadow-sm">{business.name.charAt(0).toUpperCase()}</div>}<div className="pb-1"><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight text-foreground md:text-4xl">{business.name}</h1>{business.is_verified?<span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><BadgeCheck className="size-4"/>Verified</span>:null}{business.is_hiring?<span className="rounded-full bg-accent/60 px-3 py-1 text-xs font-semibold text-accent-foreground">Hiring</span>:null}</div><p className="mt-2 text-muted-foreground">{business.category}</p>{location?<p className="mt-1 text-sm text-muted-foreground">{location}</p>:null}</div></div>
   {business.short_description?<p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{business.short_description}</p>:null}
   {canEdit||canVerify?<div className="mt-6 flex flex-wrap gap-3">{canEdit?<Link href={`/businesses/${business.slug}/edit`} className="inline-flex rounded-xl border border-border bg-card px-5 py-3 font-semibold text-foreground hover:bg-muted">Edit business</Link>:null}{canVerify?<form action={setBusinessVerification}><input type="hidden" name="business_id" value={business.id}/><input type="hidden" name="slug" value={business.slug}/><input type="hidden" name="verified" value={business.is_verified?"false":"true"}/><button type="submit" className="inline-flex rounded-xl border border-primary/25 bg-primary/5 px-5 py-3 font-semibold text-primary hover:bg-primary/10">{business.is_verified?"Remove verification":"Verify business"}</button></form>:null}</div>:null}
   </div>
  </section>
  <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6">{business.description?<section className="surface-panel rounded-2xl p-6 md:p-8"><h2 className="text-2xl font-semibold text-foreground">About</h2><p className="mt-4 whitespace-pre-line leading-8 text-muted-foreground">{business.description}</p></section>:null}{services.length?<section className="surface-panel rounded-2xl p-6 md:p-8"><h2 className="text-2xl font-semibold text-foreground">Services</h2><div className="mt-5 flex flex-wrap gap-3">{services.map(service=><span key={service} className="rounded-full border border-border bg-muted/50 px-4 py-2 text-sm text-muted-foreground">{service}</span>)}</div></section>:null}</div>
  <aside className="surface-panel h-fit rounded-2xl p-6"><h2 className="text-lg font-semibold text-foreground">Contact</h2><div className="mt-5 space-y-4 text-sm">{business.website_url?<div><p className="text-muted-foreground">Website</p><a href={business.website_url} target="_blank" rel="noreferrer" className="mt-1 block break-words font-medium text-primary hover:underline">{business.website_url}</a></div>:null}{business.email?<div><p className="text-muted-foreground">Email</p><a href={`mailto:${business.email}`} className="mt-1 block break-words text-foreground hover:text-primary">{business.email}</a></div>:null}{business.phone?<div><p className="text-muted-foreground">Phone</p><a href={`tel:${business.phone}`} className="mt-1 block text-foreground hover:text-primary">{business.phone}</a></div>:null}{business.address_line?<div><p className="text-muted-foreground">Address</p><p className="mt-1 text-foreground">{business.address_line}</p></div>:null}{location?<div><p className="text-muted-foreground">Location</p><p className="mt-1 text-foreground">{location}</p></div>:null}</div></aside></div>
 </div></main>;
}
