import Link from "next/link";
import { ArrowUpRight, Building2, Search } from "lucide-react";
import { BusinessDirectory } from "@/components/businesses/business-directory";
import { createClient } from "@/lib/supabase/server";
import {
  catalogCheckboxInputClass,
  catalogCheckboxLabelClass,
  catalogClearClass,
  catalogFieldClass,
  catalogFilterPanelClass,
  catalogSubmitClass,
} from "@/components/catalog/catalog-filter-styles";
type BusinessesPageProps={searchParams:Promise<{q?:string|string[];category?:string|string[];city?:string|string[];hiring?:string|string[];verified?:string|string[]}>};
function getSearchValue(value:string|string[]|undefined,maxLength=100){return typeof value==="string"?value.trim().slice(0,maxLength):""} function escapeLikePattern(value:string){return value.replace(/[\\%_]/g,"\\$&")}
export default async function BusinessesPage({searchParams}:BusinessesPageProps){const params=await searchParams;const search=getSearchValue(params.q);const category=getSearchValue(params.category,80);const city=getSearchValue(params.city,80);const hiring=getSearchValue(params.hiring,20)==="only";const verified=getSearchValue(params.verified,20)==="only";const supabase=await createClient();let query=supabase.from("businesses").select(`id,name,slug,category,short_description,city,province_state,country,services,logo_url,is_verified,is_hiring`).eq("status","published").order("name",{ascending:true});if(search)query=query.ilike("name",`%${escapeLikePattern(search)}%`);if(category)query=query.ilike("category",`%${escapeLikePattern(category)}%`);if(city)query=query.ilike("city",`%${escapeLikePattern(city)}%`);if(hiring)query=query.eq("is_hiring",true);if(verified)query=query.eq("is_verified",true);const{data:businesses,error}=await query;const hasFilters=Boolean(search||category||city||hiring||verified);
return <main data-illustration-focus-scope className="px-4 py-8 sm:px-6 md:px-8 lg:px-10 lg:py-10 xl:px-12"><div className="mx-auto w-full max-w-[1500px]"><section className="relative border-b border-border pb-7 md:pb-9"><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/[0.06] px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Building2 className="size-3.5" aria-hidden="true"/>Community businesses</div><h1 className="mt-5 text-3xl font-medium tracking-[-0.035em] text-foreground md:text-4xl">Discover businesses</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">Support Afghan-owned businesses, services, and entrepreneurs in the community.</p></div><div className="flex flex-col items-start gap-5 lg:items-end"><Link href="/businesses/new" className="inline-flex w-fit items-center gap-2 rounded-[var(--radius)] bg-primary px-5 py-3 font-semibold text-primary-foreground transition hover:-translate-y-0.5 hover:bg-primary/92 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Create business<ArrowUpRight className="size-4" aria-hidden="true"/></Link></div></div></section>
<form action="/businesses" method="get" className={`${catalogFilterPanelClass} md:grid-cols-2 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)_minmax(0,1fr)_auto_auto_auto]`}><label className="grid gap-2 text-sm font-medium text-foreground"><span className="inline-flex items-center gap-2"><Search className="size-4 text-primary" aria-hidden="true"/>Search businesses</span><input type="search" name="q" defaultValue={search} placeholder="Business name" className={catalogFieldClass}/></label><label className="grid gap-2 text-sm font-medium text-foreground">Category<input type="search" name="category" defaultValue={category} placeholder="Any category" className={catalogFieldClass}/></label><label className="grid gap-2 text-sm font-medium text-foreground">City<input type="search" name="city" defaultValue={city} placeholder="Any city" className={catalogFieldClass}/></label><label className={catalogCheckboxLabelClass}><input type="checkbox" name="hiring" value="only" defaultChecked={hiring} className={catalogCheckboxInputClass}/>Hiring now</label><label className={catalogCheckboxLabelClass}><input type="checkbox" name="verified" value="only" defaultChecked={verified} className={catalogCheckboxInputClass}/>Verified listings</label><div className="flex items-end gap-3"><button type="submit" className={catalogSubmitClass}>Apply</button>{hasFilters?<Link href="/businesses" className={catalogClearClass}>Clear</Link>:null}</div></form>
<div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-muted-foreground">{error?"Businesses could not be loaded.":`${businesses?.length??0} ${businesses?.length===1?"business":"businesses"} found`}</p>{hasFilters?<p className="text-xs text-muted-foreground">Filters are reflected in the URL, so this view can be shared.</p>:null}</div>{error?<div role="alert" aria-live="assertive" className="relative mt-8 overflow-hidden rounded-[var(--radius)] border border-destructive/20 bg-destructive/5 p-5 text-sm text-destructive"><div aria-hidden="true" className="pointer-events-none absolute -right-10 -top-10 size-28 rounded-full bg-destructive/[0.06] blur-3xl"/><span className="relative">We could not load businesses. Please try again.</span></div>:businesses?.length?<BusinessDirectory businesses={businesses}/>:<div className="surface-panel relative mt-10 overflow-hidden rounded-[var(--radius)] border-dashed p-10 text-center shadow-[0_1px_0_rgb(48_43_53/0.025)]"><div aria-hidden="true" className="pointer-events-none absolute -right-12 -top-12 size-40 rounded-full bg-primary/[0.06] blur-3xl"/><span className="relative mx-auto flex size-14 items-center justify-center rounded-[var(--radius)] bg-primary/10 text-primary"><Building2 aria-hidden="true" className="size-7"/></span><h2 className="relative mt-5 text-xl font-semibold text-foreground">{hasFilters?"No businesses match these filters":"No businesses yet"}</h2><p className="relative mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{hasFilters?"Try adjusting or clearing your filters.":"Community businesses will appear here once they are added."}</p>{hasFilters?<Link href="/businesses" className="relative mt-5 inline-flex rounded-[var(--radius)] border border-border px-4 py-2 text-sm font-semibold text-foreground transition hover:-translate-y-0.5 hover:bg-muted focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Clear filters</Link>:<Link href="/businesses/new" className="relative mt-6 inline-flex rounded-[var(--radius)] bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Add a business</Link>}</div>}</div></main>}
