import { setOrganizationVerification } from "@/app/(dashboard)/organizations/actions";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck } from "lucide-react";
import { ExternalImage } from "@/components/ui/external-image";
import { getMyAccessContext } from "@/lib/profile-access";
import { createClient } from "@/lib/supabase/server";

type OrganizationPageProps={params:Promise<{slug:string}>;searchParams:Promise<{error?:string}>};
export default async function OrganizationPage({params,searchParams}:OrganizationPageProps){
 const {slug}=await params; const {error:actionError}=await searchParams; const supabase=await createClient();
 const {data:organization,error}=await supabase.from("organizations").select(`id,name,slug,short_description,description,organization_type,mission,programs,website_url,email,phone,city,province_state,country,logo_url,cover_url,is_verified,is_accepting_volunteers,status,moderation_note,owner_id`).eq("slug",slug).maybeSingle();
 if(error||!organization)notFound();
 const {data:{user}}=await supabase.auth.getUser();
 const {data:viewerProfile}=user?await getMyAccessContext(supabase,user.id):{data:null};
 const canEdit=user?.id===organization.owner_id; const canVerify=viewerProfile?.role==="admin"&&organization.status==="published";
 const programs=Array.isArray(organization.programs)?organization.programs.filter((program:unknown):program is string=>typeof program==="string"):[];
 const location=[organization.city,organization.province_state,organization.country].filter(Boolean).join(", ");
 return <main className="px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl">
  <Link href="/organizations" className="text-sm font-medium text-primary hover:opacity-80">← Back to organizations</Link>
  {actionError?<div className="mt-6 rounded-xl border border-destructive/20 bg-destructive/5 p-4 text-sm text-destructive">{actionError}</div>:null}
  {organization.status!=="published"?<div className="mt-6 rounded-xl border border-accent/50 bg-accent/40 p-4 text-sm text-accent-foreground">{organization.status==="draft"?"This organization is waiting for moderator approval and is not visible to the community yet.":`This organization was not approved.${organization.moderation_note?` Reason: ${organization.moderation_note}`:""} Edit it to submit it for review again.`}</div>:null}
  <section className="surface-panel mt-6 overflow-hidden rounded-3xl">{organization.cover_url?<ExternalImage src={organization.cover_url} alt={`${organization.name} cover`} width={1200} height={400} className="h-40 w-full object-cover md:h-56"/>:<div className="h-40 bg-[radial-gradient(circle_at_20%_20%,color-mix(in_oklab,var(--primary)_12%,transparent),transparent_35%),linear-gradient(to_right,var(--muted),var(--card))] md:h-56"/>}
   <div className="px-6 pb-8 md:px-10"><div className="-mt-12 flex flex-col gap-5 sm:flex-row sm:items-end">{organization.logo_url?<ExternalImage src={organization.logo_url} alt={`${organization.name} logo`} width={96} height={96} className="size-24 rounded-2xl border-4 border-card object-cover shadow-sm"/>:<div className="flex size-24 items-center justify-center rounded-2xl border-4 border-card bg-primary/10 text-3xl font-bold text-primary shadow-sm">{organization.name.charAt(0).toUpperCase()}</div>}
    <div className="pb-1"><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight text-foreground md:text-4xl">{organization.name}</h1>{organization.is_verified?<span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><BadgeCheck className="size-4"/>Verified</span>:null}</div>{organization.organization_type?<p className="mt-2 text-muted-foreground">{organization.organization_type}</p>:null}{location?<p className="mt-1 text-sm text-muted-foreground">{location}</p>:null}</div></div>
    {organization.short_description?<p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{organization.short_description}</p>:null}
    {canEdit||canVerify?<div className="mt-6 flex flex-wrap gap-3">{canEdit?<Link href={`/organizations/${organization.slug}/edit`} className="inline-flex rounded-xl border border-border bg-card px-5 py-3 font-semibold text-foreground hover:bg-muted">Edit organization</Link>:null}{canVerify?<form action={setOrganizationVerification}><input type="hidden" name="organization_id" value={organization.id}/><input type="hidden" name="slug" value={organization.slug}/><input type="hidden" name="verified" value={organization.is_verified?"false":"true"}/><button type="submit" className="inline-flex rounded-xl border border-primary/25 bg-primary/5 px-5 py-3 font-semibold text-primary hover:bg-primary/10">{organization.is_verified?"Remove verification":"Verify organization"}</button></form>:null}</div>:null}
   </div>
  </section>
  <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6">{organization.description?<section className="surface-panel rounded-2xl p-6 md:p-8"><h2 className="text-2xl font-semibold text-foreground">About</h2><p className="mt-4 whitespace-pre-line leading-8 text-muted-foreground">{organization.description}</p></section>:null}{organization.mission?<section className="surface-panel rounded-2xl p-6 md:p-8"><h2 className="text-2xl font-semibold text-foreground">Mission</h2><p className="mt-4 whitespace-pre-line leading-8 text-muted-foreground">{organization.mission}</p></section>:null}{programs.length?<section className="surface-panel rounded-2xl p-6 md:p-8"><h2 className="text-2xl font-semibold text-foreground">Programs</h2><div className="mt-5 flex flex-wrap gap-3">{programs.map(program=><span key={program} className="rounded-full border border-border bg-muted/50 px-4 py-2 text-sm text-muted-foreground">{program}</span>)}</div></section>:null}</div>
   <aside className="surface-panel h-fit rounded-2xl p-6"><h2 className="text-lg font-semibold text-foreground">Contact</h2><div className="mt-5 space-y-4 text-sm">{organization.website_url?<div><p className="text-muted-foreground">Website</p><a href={organization.website_url} target="_blank" rel="noreferrer" className="mt-1 block break-words font-medium text-primary hover:underline">{organization.website_url}</a></div>:null}{organization.email?<div><p className="text-muted-foreground">Email</p><a href={`mailto:${organization.email}`} className="mt-1 block break-words text-foreground hover:text-primary">{organization.email}</a></div>:null}{organization.phone?<div><p className="text-muted-foreground">Phone</p><a href={`tel:${organization.phone}`} className="mt-1 block text-foreground hover:text-primary">{organization.phone}</a></div>:null}{location?<div><p className="text-muted-foreground">Location</p><p className="mt-1 text-foreground">{location}</p></div>:null}{organization.is_accepting_volunteers?<div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-primary">This organization is accepting volunteers.</div>:null}</div></aside>
  </div>
 </div></main>;
}
