import formStyles from "@/components/forms/listing-form.module.css";
import { CommunitySignature } from "@/components/public/community-signature";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { EventDateTimePicker } from "@/components/ui/event-date-time-picker";
import { createEvent } from "../actions";

export default async function NewEventPage(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:organizations}=await supabase.from("organizations").select("id, name").eq("owner_id",user.id).order("name");const field="mt-2 w-full rounded-xl border border-border bg-card px-4 py-3 text-foreground outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";return <main className={`${formStyles.page} mx-auto max-w-4xl px-4 py-8 md:px-8 md:py-10`}><section className="relative overflow-hidden rounded-[var(--radius)] border border-border/80 bg-card px-6 py-8 md:px-8 md:py-10"><CommunitySignature className={formStyles.signature} /><div className="relative"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Create and share</p><h1 className="mt-3 text-3xl font-medium tracking-[-0.035em] text-foreground md:text-4xl">Create an Event</h1><p className="mt-3 text-muted-foreground">Share an in-person or online event with the Afghan Hub community.</p><p className="mt-4 inline-flex rounded-full border border-primary/15 bg-primary/[0.06] px-3 py-1.5 text-sm font-medium text-primary">Your submission will be reviewed before it appears publicly.</p></div></section><form action={createEvent} className="surface-panel mt-8 space-y-8 rounded-[var(--radius)] p-6 md:p-8">
<div><label htmlFor="title" className="block text-sm font-medium text-foreground">Event title</label><input id="title" name="title" type="text" required className={field}/></div>
<div><label htmlFor="organization_id" className="block text-sm font-medium text-foreground">Hosted by</label><select id="organization_id" name="organization_id" className={field}><option value="">Personal / No organization</option>{organizations?.map((organization)=><option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></div>
<div><label htmlFor="summary" className="block text-sm font-medium text-foreground">Short summary</label><textarea id="summary" name="summary" rows={3} required className={field}/></div>
<div><label htmlFor="description" className="block text-sm font-medium text-foreground">Full description</label><textarea id="description" name="description" rows={8} required className={field}/></div>
<div className="grid gap-6 md:grid-cols-2"><div><label className="block text-sm font-medium text-foreground">Starts at</label><div className="mt-2"><EventDateTimePicker name="starts_at" label="Select start date & time" required/></div></div><div><label className="block text-sm font-medium text-foreground">Ends at</label><div className="mt-2"><EventDateTimePicker name="ends_at" label="Select end date & time"/></div></div></div>
<div><label htmlFor="venue_name" className="block text-sm font-medium text-foreground">Venue name</label><input id="venue_name" name="venue_name" type="text" className={field}/></div><div><label htmlFor="address_line" className="block text-sm font-medium text-foreground">Address</label><input id="address_line" name="address_line" type="text" className={field}/></div>
<div className="grid gap-6 md:grid-cols-3"><div><label htmlFor="city" className="block text-sm font-medium text-foreground">City</label><input id="city" name="city" type="text" className={field}/></div><div><label htmlFor="province_state" className="block text-sm font-medium text-foreground">Province / State</label><input id="province_state" name="province_state" type="text" className={field}/></div><div><label htmlFor="country" className="block text-sm font-medium text-foreground">Country</label><input id="country" name="country" type="text" className={field}/></div></div>
<label className="flex items-center gap-3 rounded-[var(--radius)] border border-border/80 bg-secondary/40 p-4 text-sm font-medium text-foreground transition hover:border-primary/20"><input name="is_online" type="checkbox" className="size-5 shrink-0 rounded border-border accent-primary focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"/><span>Online event</span></label><div><label htmlFor="online_url" className="block text-sm font-medium text-foreground">Online event link</label><input id="online_url" name="online_url" type="url" className={field}/></div><div><label htmlFor="capacity" className="block text-sm font-medium text-foreground">Capacity</label><input id="capacity" name="capacity" type="number" min="1" className={field}/></div><div className="flex justify-end border-t border-border pt-6"><button type="submit" className="rounded-[var(--radius)] bg-primary px-5 py-3 font-semibold text-primary-foreground transition hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Submit for Review</button></div></form></main>}
