import Link from "next/link";
import styles from "@/components/network/network-surfaces.module.css";
import { CommunitySignature } from "@/components/public/community-signature";
import { ArrowUpRight, Building2, MapPin } from "lucide-react";
import { ExternalImage } from "@/components/ui/external-image";
import { VerificationBadge } from "@/components/ui/verification-badge";

type Business={id:string;name:string;slug:string;category:string;short_description:string|null;city:string|null;province_state:string|null;country:string|null;services:string[];logo_url:string|null;is_verified:boolean;is_hiring:boolean};
type BusinessDirectoryProps={businesses:Business[]};
export function BusinessDirectory({businesses}:BusinessDirectoryProps){
 if(!businesses.length)return <div className={`${styles.surface} border border-border bg-card relative mt-10 overflow-hidden rounded-[var(--radius)] p-10 text-center `}><span className="relative mx-auto flex size-14 items-center justify-center rounded-[var(--radius)] bg-primary/10 text-primary"><Building2 aria-hidden="true" className="size-7"/></span><h2 className="relative mt-5 text-xl font-semibold text-foreground">No businesses yet</h2><p className="relative mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Community businesses will appear here once they are added.</p><Link href="/businesses/new" className={`${styles.control} inline-flex items-center relative mt-6 inline-flex rounded-[var(--radius)] bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground  transition  hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary`}>Add a business</Link></div>;
 return <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{businesses.map((business)=>{const location=[business.city,business.province_state,business.country].filter(Boolean).join(", ");return <Link key={business.id} href={`/businesses/${business.slug}`} className={`${styles.surface} ${styles.profile} border border-border bg-card group relative overflow-hidden rounded-[var(--radius)] p-5 transition duration-200  hover:border-primary/30  focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary`}>
  
  <CommunitySignature className={styles.signature} />
  <div className="relative flex items-start gap-4">{business.logo_url?<ExternalImage src={business.logo_url} alt={`${business.name} logo`} width={52} height={52} className="size-13 rounded-[var(--radius)] border border-border object-cover"/>:<div className="flex size-13 shrink-0 items-center justify-center rounded-[var(--radius)] bg-primary/10 text-lg font-bold text-primary">{business.name.charAt(0).toUpperCase()}</div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="line-clamp-2 break-words text-lg font-semibold leading-6 text-foreground transition group-hover:text-primary">{business.name}</h2>{business.is_verified?<VerificationBadge compact/>:null}</div><p className="mt-1 text-sm text-muted-foreground">{business.category}</p></div><ArrowUpRight data-profile-arrow aria-hidden="true" className="mt-1 size-4 shrink-0 text-muted-foreground"/></div>
  {business.short_description?<p className="relative mt-4 line-clamp-2 break-words leading-6 text-muted-foreground">{business.short_description}</p>:<p className="relative mt-4 text-sm text-muted-foreground">No description provided.</p>}
  {business.services.length?<div className="relative mt-4 flex flex-wrap gap-2">{business.services.slice(0,3).map((service)=><span key={service} className="rounded-full border border-border bg-muted/50 px-3 py-1 text-xs text-muted-foreground">{service}</span>)}</div>:null}
  <div className="relative mt-4 flex flex-wrap items-center gap-2 border-t border-border/70 pt-4 text-sm text-muted-foreground">{location?<span className="inline-flex min-w-0 items-start gap-1.5"><MapPin aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary"/><span className="min-w-0 break-words">{location}</span></span>:null}{business.is_hiring?<span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">Hiring now</span>:null}</div>
 </Link>})}</div>;
}
