import Link from "next/link";
import { ArrowUpRight, Building2, MapPin } from "lucide-react";
import { ExternalImage } from "@/components/ui/external-image";
import { VerificationBadge } from "@/components/ui/verification-badge";

type Business={id:string;name:string;slug:string;category:string;short_description:string|null;city:string|null;province_state:string|null;country:string|null;services:string[];logo_url:string|null;is_verified:boolean;is_hiring:boolean};
type BusinessDirectoryProps={businesses:Business[]};
export function BusinessDirectory({businesses}:BusinessDirectoryProps){
 if(!businesses.length)return <div className="surface-panel relative mt-10 overflow-hidden rounded-[2rem] p-10 text-center shadow-[0_14px_42px_rgb(15_23_42/0.04)]"><div aria-hidden="true" className="pointer-events-none absolute -right-12 -top-12 size-40 rounded-full bg-primary/[0.06] blur-3xl"/><span className="relative mx-auto flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Building2 aria-hidden="true" className="size-7"/></span><h2 className="relative mt-5 text-xl font-semibold text-foreground">No businesses yet</h2><p className="relative mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Community businesses will appear here once they are added.</p><Link href="/businesses/new" className="relative mt-6 inline-flex rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Add a business</Link></div>;
 return <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{businesses.map((business)=>{const location=[business.city,business.province_state,business.country].filter(Boolean).join(", ");return <Link key={business.id} href={`/businesses/${business.slug}`} className="surface-panel group relative overflow-hidden rounded-[1.75rem] p-6 transition duration-200 hover:-translate-y-1 hover:border-primary/30 hover:shadow-[0_18px_42px_rgb(15_23_42/0.07)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">
  <div aria-hidden="true" className="absolute -right-10 -top-10 size-28 rounded-full border border-primary/10"/>
  <div className="relative flex items-start gap-4">{business.logo_url?<ExternalImage src={business.logo_url} alt={`${business.name} logo`} width={56} height={56} className="size-14 rounded-2xl border border-border object-cover"/>:<div className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-lg font-bold text-primary">{business.name.charAt(0).toUpperCase()}</div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="line-clamp-2 break-words text-lg font-semibold leading-6 text-foreground transition group-hover:text-primary">{business.name}</h2>{business.is_verified?<VerificationBadge compact/>:null}</div><p className="mt-1 break-words text-sm text-muted-foreground">{business.category}</p></div><ArrowUpRight aria-hidden="true" className="mt-1 size-4 shrink-0 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary"/></div>
  {business.short_description?<p className="relative mt-5 line-clamp-3 break-words leading-6 text-muted-foreground">{business.short_description}</p>:<p className="relative mt-5 text-sm text-muted-foreground">No description provided.</p>}
  {business.services.length?<div className="relative mt-5 flex flex-wrap gap-2">{business.services.slice(0,4).map((service)=><span key={service} className="max-w-full break-words rounded-full border border-border bg-muted/50 px-3 py-1 text-xs text-muted-foreground">{service}</span>)}</div>:null}
  <div className="relative mt-5 flex flex-wrap items-center gap-2 border-t border-border/70 pt-4 text-sm text-muted-foreground">{location?<span className="inline-flex min-w-0 items-start gap-1.5"><MapPin aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary"/><span className="min-w-0 break-words">{location}</span></span>:null}{business.is_hiring?<span className="max-w-full break-words rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">Hiring now</span>:null}</div>
 </Link>})}</div>;
}
