import { CatalogIllustration } from "@/components/public/catalog-illustration";
import styles from "@/components/network/network-surfaces.module.css";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, ExternalLink, Globe2, HandHeart, Languages, MapPin, UserRound } from "lucide-react";
import { RecommendedMembers } from "@/components/dashboard/recommended-members";
import { ConnectionButton } from "@/components/network/connection-button";
import { ExternalImage } from "@/components/ui/external-image";
import { rankMemberRecommendations } from "@/lib/member-recommendations";
import { createClient } from "@/lib/supabase/server";

type MemberProfilePageProps={params:Promise<{id:string}>};
function getMemberName(profile:{display_name:string|null;first_name:string|null;last_name:string|null}){return profile.display_name?.trim()||[profile.first_name,profile.last_name].filter(Boolean).join(" ")||"Afghan Hub Member"}
function getInitials(name:string){return name.split(" ").filter(Boolean).slice(0,2).map((part)=>part.charAt(0).toUpperCase()).join("")}
function normalizeExternalUrl(url:string){return url.startsWith("http://")||url.startsWith("https://")?url:`https://${url}`}

export default async function MemberProfilePage({params}:MemberProfilePageProps){const{id}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();const{data:profile,error}=await supabase.from("profiles").select(`id,display_name,first_name,last_name,headline,profession,company,bio,city,province_state,country,avatar_url,skills,languages,website_url,linkedin_url,is_public,onboarding_completed,open_to_mentoring,looking_for_mentor,mentorship_topics`).eq("id",id).eq("is_public",true).eq("onboarding_completed",true).maybeSingle();if(error)console.error("Could not load member profile; provider details withheld.");if(!profile)notFound();const[{data:connection},{data:memberCandidates}]=await Promise.all([user&&user.id!==profile.id?supabase.from("connections").select("id, requester_id, recipient_id, status").or("and(requester_id.eq."+user.id+",recipient_id.eq."+profile.id+"),and(requester_id.eq."+profile.id+",recipient_id.eq."+user.id+")").limit(1).maybeSingle():Promise.resolve({data:null}),supabase.from("profiles").select(`id,display_name,first_name,last_name,headline,profession,company,city,country,avatar_url,skills`).eq("is_public",true).eq("onboarding_completed",true).neq("id",profile.id).order("display_name",{ascending:true}).limit(24)]);const memberName=getMemberName(profile);const location=[profile.city,profile.province_state,profile.country].filter(Boolean).join(", ");const professionalDetails=[profile.profession,profile.company].filter(Boolean).join(" at ");const skills=Array.isArray(profile.skills)?profile.skills:[];const languages=Array.isArray(profile.languages)?profile.languages:[];const mentorshipTopics=Array.isArray(profile.mentorship_topics)?profile.mentorship_topics:[];const hasMentorshipSignals=profile.open_to_mentoring||profile.looking_for_mentor||mentorshipTopics.length>0;const relatedMembers=rankMemberRecommendations(profile,memberCandidates??[],3);
return <main data-illustration-focus-scope className="px-4 py-8 md:px-8 lg:py-10"><div className="mx-auto max-w-5xl"><Link href="/network" className="inline-flex min-h-11 items-center gap-2 rounded-sm text-sm font-semibold text-primary hover:underline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><ArrowLeft aria-hidden="true" className="size-4"/>Back to network</Link>
<section data-illustration-trigger className={`mt-6 overflow-hidden border ${styles.surface}`}><div aria-hidden="true" className="flex h-32 items-center justify-end border-b border-border bg-background px-6 md:h-44 md:px-10"><div className="w-48 max-w-[70%] md:w-60"><CatalogIllustration interactive kind="people" /></div></div><div className="relative z-10 px-6 pb-8 md:px-10"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="flex min-w-0 flex-col gap-5 md:flex-row md:items-start"><div className="-mt-14 shrink-0 md:-mt-16">{profile.avatar_url?<ExternalImage src={profile.avatar_url} alt={memberName} width={128} height={128} className="size-28 rounded-sm border-4 border-card bg-card object-cover md:size-32"/>:<div className="flex size-28 items-center justify-center rounded-sm border-4 border-card bg-primary/10 text-3xl font-bold text-primary md:size-32">{getInitials(memberName)||<UserRound aria-hidden="true" className="size-12"/>}</div>}</div><div className="min-w-0 pt-1 md:pt-5"><h1 className="break-words text-3xl font-medium tracking-[-0.035em] text-foreground md:text-4xl">{memberName}</h1>{profile.headline?<p className="mt-2 max-w-2xl break-words text-base leading-7 text-muted-foreground">{profile.headline}</p>:null}</div></div><div className="shrink-0 md:pt-5">{user?<ConnectionButton currentUserId={user.id} memberId={profile.id} connection={connection}/>:null}</div></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-5 text-sm text-muted-foreground">{professionalDetails?<div className="flex min-w-0 items-start gap-2"><BriefcaseBusiness aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary"/><span className="min-w-0 break-words">{professionalDetails}</span></div>:null}{location?<div className="flex min-w-0 items-start gap-2"><MapPin aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary"/><span className="min-w-0 break-words">{location}</span></div>:null}</div></div></section>
<div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-6"><section className={`border p-6 md:p-8 ${styles.surface}`}><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Profile</p><h2 className="mt-1 text-xl font-bold text-foreground">About</h2>{profile.bio?<p className="mt-4 whitespace-pre-line break-words leading-7 text-muted-foreground">{profile.bio}</p>:<p className="mt-4 text-sm leading-6 text-muted-foreground">This member has not added a biography yet.</p>}</section><section className={`border p-6 md:p-8 ${styles.surface}`}><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Expertise</p><h2 className="mt-1 text-xl font-bold text-foreground">Skills</h2>{skills.length?<div className="mt-5 flex flex-wrap gap-2">{skills.map((skill)=><span key={skill} className="max-w-full break-words rounded-full border border-primary/15 bg-primary/8 px-3 py-1.5 text-sm text-primary">{skill}</span>)}</div>:<p className="mt-4 text-sm text-muted-foreground">No skills have been added.</p>}</section></div>
<aside className="space-y-6">{hasMentorshipSignals?<section className={`border p-6 ${styles.surface}`}><div className="flex items-center gap-2"><HandHeart aria-hidden="true" className="size-5 text-primary"/><h2 className="font-bold text-foreground">Mentorship</h2></div><div className="mt-4 space-y-2">{profile.open_to_mentoring?<p className="rounded-[var(--radius)] border border-primary/15 bg-primary/8 px-3 py-2 text-sm font-medium text-primary">Open to mentoring</p>:null}{profile.looking_for_mentor?<p className="rounded-[var(--radius)] border border-border bg-muted/50 px-3 py-2 text-sm font-medium text-foreground">Looking for a mentor</p>:null}</div>{mentorshipTopics.length?<div className="mt-4 flex flex-wrap gap-2">{mentorshipTopics.map((topic)=><span key={topic} className="max-w-full break-words rounded-full border border-border px-2.5 py-1 text-xs text-muted-foreground">{topic}</span>)}</div>:null}<p className="mt-4 text-xs leading-5 text-muted-foreground">These are member-selected preferences, not a credential or endorsement by Afghan Hub.</p></section>:null}<section className={`border p-6 ${styles.surface}`}><div className="flex items-center gap-2"><Languages aria-hidden="true" className="size-5 text-primary"/><h2 className="font-bold text-foreground">Languages</h2></div>{languages.length?<div className="mt-4 flex flex-wrap gap-2">{languages.map((language)=><span key={language} className="max-w-full break-words rounded-xl bg-muted px-3 py-2 text-sm text-foreground">{language}</span>)}</div>:<p className="mt-4 text-sm text-muted-foreground">No languages added.</p>}</section>{profile.website_url||profile.linkedin_url?<section className={`border p-6 ${styles.surface}`}><div className="flex items-center gap-2"><Globe2 aria-hidden="true" className="size-5 text-primary"/><h2 className="font-bold text-foreground">Links</h2></div><div className="mt-4 space-y-3">{profile.website_url?<a href={normalizeExternalUrl(profile.website_url)} target="_blank" rel="noreferrer" className={`flex items-center justify-between gap-3 border border-border bg-card px-4 py-3 text-sm text-foreground hover:border-primary/40 hover:bg-muted ${styles.control}`}><span className="flex items-center gap-2"><Globe2 aria-hidden="true" className="size-4"/>Website</span><ExternalLink aria-hidden="true" className="size-4"/></a>:null}{profile.linkedin_url?<a href={normalizeExternalUrl(profile.linkedin_url)} target="_blank" rel="noreferrer" className={`flex items-center justify-between gap-3 border border-border bg-card px-4 py-3 text-sm text-foreground hover:border-primary/40 hover:bg-muted ${styles.control}`}><span className="flex items-center gap-2"><ExternalLink aria-hidden="true" className="size-4"/>LinkedIn</span><ExternalLink aria-hidden="true" className="size-4"/></a>:null}</div></section>:null}</aside></div>
<div className="mt-6"><RecommendedMembers members={relatedMembers} eyebrow="More people to discover" title="Members with similar skills, work or location"/></div></div></main>}
