import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CalendarDays, Building2, UsersRound } from "lucide-react";
import { getPublicListings } from "@/lib/public-content";
import { publicCategories, publicKinds } from "@/lib/public-catalog";
import { ListingCard } from "@/components/public/listing-card";

const description = "Find opportunities, events, Afghan businesses, and community organizations. Explore Afghan Hub and connect with your community.";
export const metadata: Metadata = { title: "A community to belong to. A place to grow.", description, alternates: { canonical: "https://app.apnbc.ca/" }, openGraph: { title: "Afghan Hub — People, possibilities, belonging", description, url: "https://app.apnbc.ca/", type: "website" } };
const icons = [BriefcaseBusiness, CalendarDays, Building2, UsersRound];

export default async function PublicHome() {
  const feeds = await Promise.all(publicKinds.map(kind => getPublicListings(kind, { limit: 3 })));
  return <main id="main-content">
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.35fr_1fr] lg:items-center lg:gap-20">
      <div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">People. Possibilities. Belonging.</p><h1 className="mt-6 max-w-3xl text-4xl font-semibold leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Rooted in community.<br /><span className="text-primary">Growing together.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Discover the people, businesses, and opportunities shaping our Afghan community. Find your next step. Make a connection. Bring something of your own.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/explore" className="inline-flex items-center gap-3 rounded-xl bg-primary px-6 py-3.5 font-semibold text-primary-foreground hover:bg-primary/90">Explore the community <ArrowRight aria-hidden="true" className="size-4" /></Link><Link href="/login?mode=join" className="rounded-xl border border-border px-6 py-3.5 font-semibold hover:bg-muted">Join Afghan Hub</Link></div><p className="mt-4 text-xs text-muted-foreground">Start exploring. No account needed.</p></div>
      <div className="rounded-3xl border border-border bg-accent/40 p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-primary">Find your place</p><div className="mt-5 divide-y divide-border">{publicKinds.map((kind, i) => { const Icon = icons[i]; return <Link key={kind} href={`/explore?type=${kind}`} className="group flex items-start gap-4 py-5 first:pt-0 last:pb-0"><Icon aria-hidden="true" className="mt-1 size-5 shrink-0 text-primary" /><div className="flex-1"><h2 className="font-semibold group-hover:underline">{publicCategories[kind].label}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{publicCategories[kind].description}</p></div><ArrowRight aria-hidden="true" className="mt-1 size-4 shrink-0 text-primary" /></Link>; })}</div></div>
    </section>
    <div className="border-y border-border bg-card"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><p className="text-sm leading-7 text-muted-foreground"><span className="font-semibold text-foreground">A shared place, wherever you are.</span> From a first introduction to a new opportunity, community starts with showing up for one another.</p></div></div>
    <div className="mx-auto max-w-7xl space-y-16 px-5 py-16 sm:px-8">{publicKinds.map((kind, i) => <section key={kind} aria-labelledby={`${kind}-heading`}><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">{kind === "events" ? "Coming together" : kind === "opportunities" ? "Your next chapter" : "Meet the community"}</p><h2 id={`${kind}-heading`} className="mt-2 text-3xl font-semibold tracking-tight">{publicCategories[kind].label}</h2></div><Link href={`/explore?type=${kind}`} className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">Explore {publicCategories[kind].label.toLowerCase()} <ArrowRight aria-hidden="true" className="size-4" /></Link></div>{feeds[i].unavailable ? <p role="status" className="rounded-2xl border border-border p-6 text-sm text-muted-foreground">We couldn’t load these listings right now. Please try again shortly.</p> : feeds[i].items.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{feeds[i].items.map(item => <ListingCard key={item.slug} item={item} kind={kind} />)}</div> : <div className="rounded-2xl border border-dashed border-border p-8"><p className="font-medium">{kind === "events" ? "New gatherings are on the horizon." : kind === "opportunities" ? "The next opportunity starts with someone sharing it." : "Help this part of our community grow."}</p><p className="mt-2 text-sm text-muted-foreground">{kind === "events" ? "No upcoming events are listed right now." : "No current listings yet. Check back soon or join to contribute."}</p><Link href="/login?mode=join" className="mt-4 inline-block text-sm font-semibold text-primary hover:underline">Join and contribute →</Link></div>}</section>)}</div>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 py-14 sm:px-8 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold tracking-tight">You have a place here.</h2><p className="mt-3 max-w-xl leading-7 opacity-90">Build your profile, connect with members, and share what’s happening in your corner of the community.</p></div><Link href="/login?mode=join" className="shrink-0 rounded-xl bg-background px-6 py-3.5 font-semibold text-primary hover:bg-background/90">Join Afghan Hub</Link></div></section>
  </main>;
}
